[package]
name = "NQueens"
version = "0.1.0"
authors = ["Pranav Putta <pranavputta@gatech.edu>"]
edition = "2018"

[profile.release]
debug = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
indicatif = "0.16.2"